### ISSUE TITLE
Plans to publish to npm?

### ISSUE THREAD

**Issue by bsmoliak** [AdaskoTheBeAsT/angular-gherkin-testcafe-builder#1]
@AdaskoTheBeAsT any updates on publishing `angular-gherkin-testcafe-builder` to npm? I'm looking to transition from protractor to gherkin-testcafe. Your builder is the missing link for several of my angular projects.

**Comment by AdaskoTheBeAsT** [comment]
hi - I will update project and publish it probably during weekend

**Comment by AdaskoTheBeAsT** [comment]
Published
